# Generated by Django 4.2.5 on 2023-09-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='skills_images')),
                ('skill', models.CharField(max_length=150)),
                ('years', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-years'],
            },
        ),
    ]
