# Generated by Django 4.2.5 on 2023-10-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
