# Generated by Django 4.2.5 on 2023-10-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='link_details',
            field=models.CharField(blank=True, default='Link', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='link_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
