# Generated by Django 4.2.5 on 2023-10-02 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='portfolio_images')),
                ('details', models.TextField()),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CodeLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(max_length=250)),
                ('info', models.CharField(max_length=200)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codelinks', to='portfolio.display')),
            ],
        ),
    ]
