# Generated by Django 4.2.5 on 2023-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='work',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
