# Generated by Django 4.2.5 on 2023-09-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0002_workexperience_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['start_date', 'end_date']},
        ),
    ]
